version: '3'

services:
  ts-task-manager-api:
    container_name: ts-task-manager-api
    image: ts-task-manager-api-dev:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '8081:8081'
    env_file:
      - .env
    depends_on:
      - mongodb
    command: npm run dev

  mongodb:
    container_name: ts-task-manager-api-mongodb
    image: mongodb/mongodb-community-server:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: passMongoDB123
