export enum HTTPErrorType {
  INVALID_INPUT = 'INVALID_INPUT',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'
}
